# BankingApp adında database olmalı: "dbname=BankingApp user=postgres password=1234"

import psycopg2

com = """CREATE TABLE IF NOT EXISTS public.admin
(
    admin_id integer NOT NULL,
    admin_password character varying(30) COLLATE pg_catalog."default",
    CONSTRAINT "Admin_pkey" PRIMARY KEY (admin_id)
);

CREATE TABLE IF NOT EXISTS public.all_transactions
(
    customer_id integer,
    transaction_amount integer,
    transaction_type integer,
    transaction_date timestamp without time zone
);

CREATE TABLE IF NOT EXISTS public.balance
(
    customer_id integer NOT NULL,
    current_balance integer NOT NULL,
    transaction_name character varying(15) COLLATE pg_catalog."default",
    transaction_type integer
);

CREATE TABLE IF NOT EXISTS public.customer
(
    cs_name character varying(20) COLLATE pg_catalog."default",
    cs_email character varying(30) COLLATE pg_catalog."default",
    cs_password character varying(30) COLLATE pg_catalog."default",
    cs_opening_balance integer,
    admin_id integer,
    bank_id integer DEFAULT 1234,
    customer_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 12340000 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    CONSTRAINT "Customer_pkey3" PRIMARY KEY (customer_id)
);

CREATE TABLE IF NOT EXISTS public.login
(
    customer_id integer,
    tr_type integer,
    tr_date timestamp without time zone
);

ALTER TABLE IF EXISTS public.all_transactions
    ADD CONSTRAINT customer_id FOREIGN KEY (customer_id)
    REFERENCES public.customer (customer_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.balance
    ADD CONSTRAINT customer_id FOREIGN KEY (customer_id)
    REFERENCES public.customer (customer_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS "Balance_pkey"
    ON public.balance(customer_id);


ALTER TABLE IF EXISTS public.customer
    ADD CONSTRAINT admin_id FOREIGN KEY (admin_id)
    REFERENCES public.admin (admin_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.login
    ADD CONSTRAINT login_customer_id_fkey FOREIGN KEY (customer_id)
    REFERENCES public.customer (customer_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID"""


conn = psycopg2.connect("dbname=BankingApp user = postgres password=1234")
cur = conn.cursor() 
cur.execute(com)
cur.close()
conn.commit()
conn.close()