# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/melike/Documents/GitHub/BankingApp_SQL/admin_edit_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Admin_infoEdit_window(object):
    def setupUi(self, Admin_infoEdit_window):
        Admin_infoEdit_window.setObjectName("Admin_infoEdit_window")
        Admin_infoEdit_window.resize(600, 700)
        Admin_infoEdit_window.setMinimumSize(QtCore.QSize(600, 700))
        Admin_infoEdit_window.setMaximumSize(QtCore.QSize(600, 700))
        Admin_infoEdit_window.setStyleSheet("background-color: rgb(5, 130, 202);")
        self.centralwidget = QtWidgets.QWidget(Admin_infoEdit_window)
        self.centralwidget.setObjectName("centralwidget")
        self.adeditwdw_lbl_headingPers = QtWidgets.QLabel(self.centralwidget)
        self.adeditwdw_lbl_headingPers.setGeometry(QtCore.QRect(90, 140, 321, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.adeditwdw_lbl_headingPers.setFont(font)
        self.adeditwdw_lbl_headingPers.setObjectName("adeditwdw_lbl_headingPers")
        self.adeditwdw_lbl_headingCntc = QtWidgets.QLabel(self.centralwidget)
        self.adeditwdw_lbl_headingCntc.setGeometry(QtCore.QRect(90, 270, 321, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.adeditwdw_lbl_headingCntc.setFont(font)
        self.adeditwdw_lbl_headingCntc.setObjectName("adeditwdw_lbl_headingCntc")
        self.adeditwdw_lbl_email = QtWidgets.QLabel(self.centralwidget)
        self.adeditwdw_lbl_email.setGeometry(QtCore.QRect(90, 330, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.adeditwdw_lbl_email.setFont(font)
        self.adeditwdw_lbl_email.setObjectName("adeditwdw_lbl_email")
        self.adeditwdw_lbl_headingAcc = QtWidgets.QLabel(self.centralwidget)
        self.adeditwdw_lbl_headingAcc.setGeometry(QtCore.QRect(90, 400, 321, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.adeditwdw_lbl_headingAcc.setFont(font)
        self.adeditwdw_lbl_headingAcc.setObjectName("adeditwdw_lbl_headingAcc")
        self.adeditwdw_lbl_password = QtWidgets.QLabel(self.centralwidget)
        self.adeditwdw_lbl_password.setGeometry(QtCore.QRect(90, 460, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.adeditwdw_lbl_password.setFont(font)
        self.adeditwdw_lbl_password.setObjectName("adeditwdw_lbl_password")
        self.adeditwdw_btn_save = QtWidgets.QPushButton(self.centralwidget)
        self.adeditwdw_btn_save.setGeometry(QtCore.QRect(340, 580, 180, 61))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.adeditwdw_btn_save.setFont(font)
        self.adeditwdw_btn_save.setStyleSheet("QPushButton {\n"
"background-color: rgb(0, 150, 199);\n"
"   border-color: rgb(66, 167, 255);\n"
"   border-bottom-color: rgb(255, 255, 255);\n"
"   border:2px solid rgb(202, 240, 248);\n"
"   border-radius:20px;\n"
"   border-color: black;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"     background-color: rgb(202, 240, 248);\n"
"     border:2px solid rgb(202, 240, 248);\n"
"}\n"
"    \n"
"   ")
        self.adeditwdw_btn_save.setObjectName("adeditwdw_btn_save")
        self.ad_edit_wdw_cs_email_lnedit = QtWidgets.QLineEdit(self.centralwidget)
        self.ad_edit_wdw_cs_email_lnedit.setGeometry(QtCore.QRect(220, 330, 211, 51))
        self.ad_edit_wdw_cs_email_lnedit.setObjectName("ad_edit_wdw_cs_email_lnedit")
        self.ad_edit_wdw_cs_pw_lnedit = QtWidgets.QLineEdit(self.centralwidget)
        self.ad_edit_wdw_cs_pw_lnedit.setGeometry(QtCore.QRect(220, 460, 211, 51))
        self.ad_edit_wdw_cs_pw_lnedit.setObjectName("ad_edit_wdw_cs_pw_lnedit")
        self.adeditwdw_lbl_heading = QtWidgets.QLabel(self.centralwidget)
        self.adeditwdw_lbl_heading.setGeometry(QtCore.QRect(90, 70, 37, 49))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.adeditwdw_lbl_heading.setFont(font)
        self.adeditwdw_lbl_heading.setObjectName("adeditwdw_lbl_heading")
        self.ad_edit_wdw_cs_id_lnedit = QtWidgets.QLineEdit(self.centralwidget)
        self.ad_edit_wdw_cs_id_lnedit.setGeometry(QtCore.QRect(140, 70, 171, 49))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ad_edit_wdw_cs_id_lnedit.sizePolicy().hasHeightForWidth())
        self.ad_edit_wdw_cs_id_lnedit.setSizePolicy(sizePolicy)
        self.ad_edit_wdw_cs_id_lnedit.setObjectName("ad_edit_wdw_cs_id_lnedit")
        self.adeditwdw_lbl_name = QtWidgets.QLabel(self.centralwidget)
        self.adeditwdw_lbl_name.setGeometry(QtCore.QRect(90, 200, 91, 49))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.adeditwdw_lbl_name.sizePolicy().hasHeightForWidth())
        self.adeditwdw_lbl_name.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.adeditwdw_lbl_name.setFont(font)
        self.adeditwdw_lbl_name.setObjectName("adeditwdw_lbl_name")
        self.ad_edit_wdw_cs_name_lnedit = QtWidgets.QLineEdit(self.centralwidget)
        self.ad_edit_wdw_cs_name_lnedit.setGeometry(QtCore.QRect(220, 200, 211, 49))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ad_edit_wdw_cs_name_lnedit.sizePolicy().hasHeightForWidth())
        self.ad_edit_wdw_cs_name_lnedit.setSizePolicy(sizePolicy)
        self.ad_edit_wdw_cs_name_lnedit.setObjectName("ad_edit_wdw_cs_name_lnedit")
        self.ad_edit_wdw_warn_lbl = QtWidgets.QLabel(self.centralwidget)
        self.ad_edit_wdw_warn_lbl.setGeometry(QtCore.QRect(120, 529, 361, 41))
        self.ad_edit_wdw_warn_lbl.setObjectName("ad_edit_wdw_warn_lbl")
        self.adeditwdw_btn_back = QtWidgets.QPushButton(self.centralwidget)
        self.adeditwdw_btn_back.setGeometry(QtCore.QRect(90, 580, 180, 61))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.adeditwdw_btn_back.setFont(font)
        self.adeditwdw_btn_back.setStyleSheet("QPushButton {\n"
"background-color: rgb(0, 150, 199);\n"
"   border-color: rgb(66, 167, 255);\n"
"   border-bottom-color: rgb(255, 255, 255);\n"
"   border:2px solid rgb(202, 240, 248);\n"
"   border-radius:20px;\n"
"   border-color: black;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"     background-color: rgb(202, 240, 248);\n"
"     border:2px solid rgb(202, 240, 248);\n"
"}\n"
"    \n"
"   ")
        self.adeditwdw_btn_back.setObjectName("adeditwdw_btn_back")
        Admin_infoEdit_window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Admin_infoEdit_window)
        self.statusbar.setObjectName("statusbar")
        Admin_infoEdit_window.setStatusBar(self.statusbar)

        self.retranslateUi(Admin_infoEdit_window)
        QtCore.QMetaObject.connectSlotsByName(Admin_infoEdit_window)

    def retranslateUi(self, Admin_infoEdit_window):
        _translate = QtCore.QCoreApplication.translate
        Admin_infoEdit_window.setWindowTitle(_translate("Admin_infoEdit_window", "MainWindow"))
        self.adeditwdw_lbl_headingPers.setText(_translate("Admin_infoEdit_window", "Personal Information"))
        self.adeditwdw_lbl_headingCntc.setText(_translate("Admin_infoEdit_window", "Contact Information"))
        self.adeditwdw_lbl_email.setText(_translate("Admin_infoEdit_window", "Email:"))
        self.adeditwdw_lbl_headingAcc.setText(_translate("Admin_infoEdit_window", "Account Information"))
        self.adeditwdw_lbl_password.setText(_translate("Admin_infoEdit_window", "Password:"))
        self.adeditwdw_btn_save.setText(_translate("Admin_infoEdit_window", "Save"))
        self.adeditwdw_lbl_heading.setText(_translate("Admin_infoEdit_window", "Id:"))
        self.adeditwdw_lbl_name.setText(_translate("Admin_infoEdit_window", "Name:"))
        self.ad_edit_wdw_warn_lbl.setText(_translate("Admin_infoEdit_window", "TextLabel"))
        self.adeditwdw_btn_back.setText(_translate("Admin_infoEdit_window", "Back"))
