# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\musab\OneDrive\Belgeler\GitHub\BankingApp_SQL\admin_options_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_admin_options_window(object):
    def setupUi(self, admin_options_window):
        admin_options_window.setObjectName("admin_options_window")
        admin_options_window.resize(600, 700)
        admin_options_window.setMinimumSize(QtCore.QSize(600, 700))
        admin_options_window.setMaximumSize(QtCore.QSize(600, 700))
        admin_options_window.setStyleSheet("background-color: rgb(5, 130, 202);")
        self.centralwidget = QtWidgets.QWidget(admin_options_window)
        self.centralwidget.setObjectName("centralwidget")
        self.adminoptwdw_lbl_heading = QtWidgets.QLabel(self.centralwidget)
        self.adminoptwdw_lbl_heading.setGeometry(QtCore.QRect(-20, 50, 641, 81))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.adminoptwdw_lbl_heading.setFont(font)
        self.adminoptwdw_lbl_heading.setAlignment(QtCore.Qt.AlignCenter)
        self.adminoptwdw_lbl_heading.setObjectName("adminoptwdw_lbl_heading")
        self.adminwdw_btn_createcs = QtWidgets.QPushButton(self.centralwidget)
        self.adminwdw_btn_createcs.setGeometry(QtCore.QRect(139, 190, 301, 71))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.adminwdw_btn_createcs.setFont(font)
        self.adminwdw_btn_createcs.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 100, 148);\n"
"\n"
"border:2px solid rgb(0, 150, 199);\n"
"border-radius:20px;\n"
"border-color:black;\n"
"}\n"
"QPushButton:hover {\n"
"     background-color: rgb(202, 240, 248);\n"
"     border:2px solid rgb(0, 150, 199);\n"
"}")
        self.adminwdw_btn_createcs.setObjectName("adminwdw_btn_createcs")
        self.adminwdw_btn_editinf = QtWidgets.QPushButton(self.centralwidget)
        self.adminwdw_btn_editinf.setGeometry(QtCore.QRect(140, 300, 301, 71))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.adminwdw_btn_editinf.setFont(font)
        self.adminwdw_btn_editinf.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 100, 148);\n"
"\n"
"border:2px solid rgb(0, 150, 199);\n"
"border-radius:20px;\n"
"border-color:black;\n"
"}\n"
"QPushButton:hover {\n"
"     background-color: rgb(202, 240, 248);\n"
"     border:2px solid rgb(0, 150, 199);\n"
"}")
        self.adminwdw_btn_editinf.setObjectName("adminwdw_btn_editinf")
        self.adminwdw_btn_bankstt = QtWidgets.QPushButton(self.centralwidget)
        self.adminwdw_btn_bankstt.setGeometry(QtCore.QRect(140, 410, 301, 71))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.adminwdw_btn_bankstt.setFont(font)
        self.adminwdw_btn_bankstt.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 100, 148);\n"
"\n"
"border:2px solid rgb(0, 150, 199);\n"
"border-radius:20px;\n"
"border-color:black;\n"
"}\n"
"QPushButton:hover {\n"
"     background-color: rgb(202, 240, 248);\n"
"     border:2px solid rgb(0, 150, 199);\n"
"}")
        self.adminwdw_btn_bankstt.setObjectName("adminwdw_btn_bankstt")
        self.adminwdw_btn_logout = QtWidgets.QPushButton(self.centralwidget)
        self.adminwdw_btn_logout.setGeometry(QtCore.QRect(100, 590, 150, 50))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.adminwdw_btn_logout.setFont(font)
        self.adminwdw_btn_logout.setStyleSheet("QPushButton {\n"
"background-color: rgb(0, 150, 199);\n"
"   border-color: rgb(66, 167, 255);\n"
"   border-bottom-color: rgb(255, 255, 255);\n"
"   border:2px solid rgb(202, 240, 248);\n"
"   border-radius:20px;\n"
"   border-color: black;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"     background-color: rgb(202, 240, 248);\n"
"     border:2px solid rgb(202, 240, 248);\n"
"}\n"
"    \n"
"   ")
        self.adminwdw_btn_logout.setObjectName("adminwdw_btn_logout")
        self.adminwdw_btn_exit = QtWidgets.QPushButton(self.centralwidget)
        self.adminwdw_btn_exit.setGeometry(QtCore.QRect(340, 590, 150, 50))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.adminwdw_btn_exit.setFont(font)
        self.adminwdw_btn_exit.setStyleSheet("QPushButton {\n"
"background-color: rgb(0, 150, 199);\n"
"   border-color: rgb(66, 167, 255);\n"
"   border-bottom-color: rgb(255, 255, 255);\n"
"   border:2px solid rgb(202, 240, 248);\n"
"   border-radius:20px;\n"
"   border-color: black;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"     background-color: rgb(202, 240, 248);\n"
"     border:2px solid rgb(202, 240, 248);\n"
"}\n"
"    \n"
"   ")
        self.adminwdw_btn_exit.setObjectName("adminwdw_btn_exit")
        admin_options_window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(admin_options_window)
        self.statusbar.setObjectName("statusbar")
        admin_options_window.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(admin_options_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 22))
        self.menubar.setObjectName("menubar")
        admin_options_window.setMenuBar(self.menubar)

        self.retranslateUi(admin_options_window)
        QtCore.QMetaObject.connectSlotsByName(admin_options_window)

    def retranslateUi(self, admin_options_window):
        _translate = QtCore.QCoreApplication.translate
        admin_options_window.setWindowTitle(_translate("admin_options_window", "Admin Options Window"))
        self.adminoptwdw_lbl_heading.setText(_translate("admin_options_window", "Administrative Operations"))
        self.adminwdw_btn_createcs.setText(_translate("admin_options_window", "Create Customer"))
        self.adminwdw_btn_editinf.setText(_translate("admin_options_window", "Edit Customer Information"))
        self.adminwdw_btn_bankstt.setText(_translate("admin_options_window", "Statements"))
        self.adminwdw_btn_logout.setText(_translate("admin_options_window", "Log Out"))
        self.adminwdw_btn_exit.setText(_translate("admin_options_window", "Exit"))
