# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/melike/Documents/GitHub/BankingApp_SQL/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_open_window(object):
    def setupUi(self, open_window):
        open_window.setObjectName("open_window")
        open_window.resize(600, 700)
        open_window.setMinimumSize(QtCore.QSize(600, 700))
        open_window.setMaximumSize(QtCore.QSize(600, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/bank-2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        open_window.setWindowIcon(icon)
        open_window.setStyleSheet("\n"
"background-color: rgb(241, 242, 248);")
        self.centralwidget = QtWidgets.QWidget(open_window)
        self.centralwidget.setObjectName("centralwidget")
        self.openwdw_lbl_welcome = QtWidgets.QLabel(self.centralwidget)
        self.openwdw_lbl_welcome.setGeometry(QtCore.QRect(0, 60, 611, 111))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.openwdw_lbl_welcome.setFont(font)
        self.openwdw_lbl_welcome.setStyleSheet("color: rgb(15, 42, 57);")
        self.openwdw_lbl_welcome.setAlignment(QtCore.Qt.AlignCenter)
        self.openwdw_lbl_welcome.setObjectName("openwdw_lbl_welcome")
        self.openwdw_btn_CSLogin = QtWidgets.QPushButton(self.centralwidget)
        self.openwdw_btn_CSLogin.setGeometry(QtCore.QRect(171, 201, 271, 71))
        self.openwdw_btn_CSLogin.setMinimumSize(QtCore.QSize(271, 71))
        self.openwdw_btn_CSLogin.setMaximumSize(QtCore.QSize(271, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.openwdw_btn_CSLogin.setFont(font)
        self.openwdw_btn_CSLogin.setStyleSheet("QPushButton{\n"
"color: rgb(39, 82, 97);\n"
"background-color: rgb(211, 224, 243);\n"
"border:2px solid rgb(123, 169, 191);\n"
"border-radius:20px\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"     background-color: rgb(225, 229, 241);\n"
"     border:2px solid rgb(196, 218, 245);\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/login.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.openwdw_btn_CSLogin.setIcon(icon1)
        self.openwdw_btn_CSLogin.setIconSize(QtCore.QSize(50, 50))
        self.openwdw_btn_CSLogin.setObjectName("openwdw_btn_CSLogin")
        self.openwdw_btn_ADLogin = QtWidgets.QPushButton(self.centralwidget)
        self.openwdw_btn_ADLogin.setGeometry(QtCore.QRect(170, 300, 271, 71))
        self.openwdw_btn_ADLogin.setMinimumSize(QtCore.QSize(271, 71))
        self.openwdw_btn_ADLogin.setMaximumSize(QtCore.QSize(271, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.openwdw_btn_ADLogin.setFont(font)
        self.openwdw_btn_ADLogin.setStyleSheet("QPushButton{\n"
"color: rgb(39, 82, 97);\n"
"background-color: rgb(211, 224, 243);\n"
"border:2px solid rgb(123, 169, 191);\n"
"border-radius:20px\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"     background-color: rgb(225, 229, 241);\n"
"     border:2px solid rgb(196, 218, 245);\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/admin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.openwdw_btn_ADLogin.setIcon(icon2)
        self.openwdw_btn_ADLogin.setIconSize(QtCore.QSize(50, 50))
        self.openwdw_btn_ADLogin.setObjectName("openwdw_btn_ADLogin")
        self.openwdw_btn_exit = QtWidgets.QPushButton(self.centralwidget)
        self.openwdw_btn_exit.setGeometry(QtCore.QRect(220, 440, 180, 70))
        self.openwdw_btn_exit.setMinimumSize(QtCore.QSize(180, 70))
        self.openwdw_btn_exit.setMaximumSize(QtCore.QSize(180, 70))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.openwdw_btn_exit.setFont(font)
        self.openwdw_btn_exit.setStyleSheet("QPushButton{\n"
"color: rgb(39, 82, 97);\n"
"background-color: rgb(187, 207, 237);\n"
"border:2px solid rgb(123, 169, 191);\n"
"border-radius:20px\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"     background-color: rgb(225, 229, 241);\n"
"     border:2px solid rgb(196, 218, 245);\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/log-out.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.openwdw_btn_exit.setIcon(icon3)
        self.openwdw_btn_exit.setIconSize(QtCore.QSize(50, 50))
        self.openwdw_btn_exit.setObjectName("openwdw_btn_exit")
        open_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(open_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 21))
        self.menubar.setObjectName("menubar")
        open_window.setMenuBar(self.menubar)

        self.retranslateUi(open_window)
        QtCore.QMetaObject.connectSlotsByName(open_window)

    def retranslateUi(self, open_window):
        _translate = QtCore.QCoreApplication.translate
        open_window.setWindowTitle(_translate("open_window", "MainWindow"))
        self.openwdw_lbl_welcome.setText(_translate("open_window", "Welcome to the Banking App"))
        self.openwdw_btn_CSLogin.setText(_translate("open_window", "  CUSTOMER LOGIN"))
        self.openwdw_btn_ADLogin.setText(_translate("open_window", "   ADMIN LOGIN"))
        self.openwdw_btn_exit.setText(_translate("open_window", "    EXIT"))
